### ISSUE TITLE
Course Creation Handled

### ISSUE THREAD

**Issue by kermitnirmit** [jcmat0/JID0138-Financial-Literacy#11]

**Comment by jcmat0** [comment]
See https://github.com/jcmat0/JID0138-Financial-Literacy/tree/jimmy/courses for progress - courses are able to be successfully created in Firebase and link properly with accounts. Once #51 is merged, this issue will automatically close.

**Comment by jcmat0** [comment]
Closing issue early just to ensure it's noted when the work was actually done. Course creation was completed as of Oct 8, 2020 at 9:19PM EDT, and course viewing was completed as of Oct 9, 2020 at 1:31AM EDT.

**Comment by jcmat0** [comment]
Apologies for any notifications this caused, I didn't realize moving an issue from "Closed" re-opened it (obvious in retrospect...)
