### ISSUE TITLE
Setup firebase hosting 

### ISSUE THREAD

**Issue by vytran9599** [jcmat0/JID0138-Financial-Literacy#25]
Connect to firebase & add dummy data for courses and users:
- 3 dummy users, each with a full name, profile image, course list, email, and visibility for email
- 5 dummy courses, each with a name

**Comment by jcmat0** [comment]
Got set up on firebase, experimented a little with dummy data on this past Sunday (Aug 30) - seems like it'll be a good solution for at least the back-end, though the hosting part will have to be handled elsewhere as the CLI did not work on my machine for whatever reason.

Will add 3 profiles and 3 dummy images, along with 5 dummy courses and data to go with them. Editing main issue comment to reflect this.

**Comment by jcmat0** [comment]
Profiles and courses added; cannot add dummy images on Firebase (requires a hosting system, so will rely on the front-end resources)
